[pytest]
; addopts = --reruns 1 --reruns-delay 2
addopts = -v --alluredir=allure-results
testpaths = tests

markers =
    ui: UI test cases
    api: API test cases
    hybrid: Hybrid UI + API tests
    smoke: Smoke suite
    regression: Regression suite
    injection(profile_name): Apply injection profile

log_cli = true
log_cli_level = INFO
