class ArghyaEntry:
    received_amount_element=""
    last_rem_date_element=""
    form_total_element=""
    difference_element=""
    payment_method_element=""
    sub_total_element=""
    occurrence_element=""
    remitter_name_element=""
    remitter_address_element=""
    remitter_difference_element=""
    remitter_state_element=""
    remitter_district_element=""
    remitter_pincode_element=""
    swast_input_element='swastyayani'
    istav_input_element="iv"
    achar_input_element=""
    daksh_input_element=""
    sanga_input_element=""
    ritwi_input_element=""
    prana_input_element=""
    anand_input_element=""
    srima_input_element=""
    add_misc_button_element=""
    misc_code_input_element="//input[@placeholder='Select miscellenious']"
    select_misc_element="//mat-option[contains(@id,'mat-option')]"
    clear_row_button_element=""
    desposit_history_button_element=""
    new_member_button_element=""
    deposit_code_button_element=""
    clear_all_buuton_element=""
    submit_entry_button_element=""
    click_member_name_element="//div[@class='member-name']//div[@class='name-field']"
    misc_arghya_input_element="//div[@class='sat-curreny-input prvrt-input']"
    misc_worker_input_element="//input[@placeholder='(Select worker name)']"
    select_misc_worker_element="//mat-option[contains(@id,'mat-option')]"


