class ReceiveLot:
    payment_method_dropdown_element="//input[@placeholder='(Select payment method)']"
    payment_method_select_dropdown_element="//span[@class='title-text' and contains(text(),'{}') ]"
    bank_name_dropdown_elememnt="//input[@placeholder='(Select your bank)']"
    bank_document_date_input_element="//input[@formcontrolname='bank_date']"
    bank_document_number_input_element="//input[@formcontrolname='bank_ref_no']"
    depositor_fc_input_element="//div[@class='lot-form ng-star-inserted']//div[1]//input[1]"
    depositor_name_input_element="//input[@placeholder='Enter the family']"
    contact_number_input_element="//input[@formcontrolname='contact_no']"
    amount_input_element="//input[@formcontrolname='amount']"
    deposite_slip_count_input_element="//input[@formcontrolname='slip_count']"
    upload_bank_document_button_element="//button[@class='sat-secondary-btn custom-upload-button ng-star-inserted'and normalize-space()='+ Upload bank document']"
    close_upload_photo_window_button_element="//div[@class='close-button']"
    attach_selected_photo_button_element="//button[@class='sat-secondary-btn ng-star-inserted' and contains (text(),'Attach selected photo')]"
    emo_depositor_name_input_element="//input[@formcontrolname='depositor_name']"
    cash_depositor_fc_input_element="(//input[@class='sat-input-control-primary ng-untouched ng-pristine ng-invalid'])[1]"
    cash_depositor_name_input_element="//input[@placeholder='Enter the family']"
    cash_contact_number_input_element="//input[@formcontrolname='contact_no']"
    receive_history_filter_button_element="//button[@class='sat-secondary-btn']"
    receive_history_search_input="//input[@placeholder='Search']" 
    filter_by_lot_no_and_date_button_element="//div[@class='side-option-title' and contains(text(),'Lot No & Date')]" 
    filter_by_lot_number_input_element="//input[@formcontrolname='lotNo']"
    filter_by_lot_received_date_input_element="//input[@formcontrolname='lotReceivedDate']" 
    filter_by_status_button_element="//div[@class='side-option-title' and contains(text(),' Status ')]"
    filter_by_status_pending_checkbox_element="(//input[contains(@id,'checkbx')])[1]"
    filter_by_status_assigned_checkbox_element="(//input[contains(@id,'checkbx')])[2]"
    filter_by_status_completd_checkbox_element="(//input[contains(@id,'checkbx')])[3]"
    filter_by_status_deleted_checkbox_element="(//input[contains(@id,'checkbx')])[4]"
    filter_by_status_printed_checkbox_element="(//input[contains(@id,'checkbx')])[5]"
    filter_by_status_unapprove_checkbox_element="(//input[contains(@id,'checkbx')])[6]"
    filter_by_status_approve_checkbox_element="(//input[contains(@id,'checkbx')])[7]"
    filter_by_status_slip_vrfd_checkbox_element="(//input[contains(@id,'checkbx')])[8]"
    filter_by_status_auto_sttld_checkbox_element="(//input[contains(@id,'checkbx')])[9]"
    filter_by_status_mnl_sttld_checkbox_element="(//input[contains(@id,'checkbx')])[10]"
    filter_by_status_slip_rjtd_checkbox_element="(//input[contains(@id,'checkbx')])[11]"
    filter_by_status_slip_miss_checkbox_element="(//input[contains(@id,'checkbx')])[12]"
    filter_by_status_bpd_miss_checkbox_element="(//input[contains(@id,'checkbx')])[13]"
    filter_by_status_sbpd_miss_checkbox_element="(//input[contains(@id,'checkbx')])[14]"
    filter_by_status_amnt_miss_checkbox_element="(//input[contains(@id,'checkbx')])[15]"
    filter_by_status_bank_miss_checkbox_element="(//input[contains(@id,'checkbx')])[16]"
    filter_by_family_code_button_element="//div[@class='side-option-title-active' and contains(text(),' Family Code ')]"
    filter_by_family_code_value_input_element="//input[@formcontrolname='familyCode']"






    upload_bank_document_uploadphoto_heading_text="//div[@class='header-text' and contains(text(),'Upload Photo')]"
    filter_lot_receive_history_heading_text="//div[@class='header-text' and contains(text(),'Filter - Lot Received history')]"