class SingleEntry:
    receive_arghya_sidebar_element="//div[contains(@class,'side-tab-title') and contains(text(),'Receive arghya')]"
    single_entry_toggle_element="//div[contains(@class,'lot-entry') and contains(text(),'Single entry')]"
    search_familycode_input_element="//input[@class='sat-input-control-primary ng-pristine ng-invalid ng-touched']"
    search_familycode_button_element="//button[@class='sat-primary-btn' and contains(text(),'Search')]"
    name_search_button_element="//button[normalize-space()='Name search (ALT+N)']"
    new_fc_button_element="//button[normalize-space()='New FC (CTRL+SHIFT+N)']"
    reset_subtotal_button_element="//button[@class='sat-secondary-btn' and contains(text(),'Reset')]"
    receive_history_filter_button_element="//span[normalize-space()='Filter']"
    receive_history_search_input_element="//input[@placeholder='Search']"
    receive_history_print_button_element="//button[@class='sat-secondary-btn' and contains(text(),' Print ')]"
    receive_history_view_button_element="//button[@class='sat-secondary-btn' and contains(text(),' View ')]"
    receive_history_reset_button_element="//button[@class='sat-secondary-btn' and contains(text(),'Reset')]"

    filter_receivd_history_payment_method_element="//div[@class='side-option-title'and contains(text(),'Payment Method')]"
    filter_receivd_history_powerjyoti_checkbox_element="//input[@id='checkbx-2']"
    filter_receivd_history_cash_checkbox_element="//input[@id='checkbx-1']"
    filter_receivd_history_timeline_button_element="//div[@class='side-option-title' and contains(text(),'Timeline')]"
    filter_receivd_history_timeline_from_date_element="//input[@formcontrolname='fromDate']"
    filter_receivd_history_timeline_to_date_element="//input[@formcontrolname='toDate']"
    filter_receivd_history_amount_button_element="//div[@class='side-option-title' and contains(text(),'Amount')]"
    filter_receivd_history_amount_from_amount_input_element="//input[@formcontrolname='fromAmount']"
    filter_receivd_history_amount_to_amount_input_element="//input[@formcontrolname='toAmount']"
    filter_receivd_history_familycode_button_element="//div[@class='side-option-title' and contains(text(),' Family Code ')]"
    filter_receivd_history_familycode_input_element="//input[@formcontrolname='familyCode']"
    filter_receivd_history_voucher_id_button_element="//div[@class='side-option-title-active' and contains(text(),' Voucher Number ')]"
    filter_receivd_history_voucher_id_AP_id_input_lement="//input[@formcontrolname='voucherNo']"
    filter_receivd_history_voucher_id_from_voucher_number_input_element="//input[@formcontrolname='fromVoucherNo']"
    filter_receivd_history_voucher_id_to_voucher_number_input_element="//input[@formcontrolname='toVoucherNo']"
    filter_receivd_history_clear_filters_button_element="//button[@class='sat-secondary-btn' and contains(text(),' Clear filters(SHIFT+ESC) ')]"
    filter_receivd_history_apply_filters_button_element="//button[@class='sat-primary-btn' and contains(text(),' Apply filters (CTRL+⏎)')]"
    filter_receivd_history_close_button_element="//div[@class='close-img']"

    

    
    receive_history_apId_header_text="//th[normalize-space()='AP ID']"
    receive_history_nameFC_header_text="//th[contains(text(),'Depositor\\'s name & FC')]"
    receive_history_payMethod_header_text="//th[contains(text(),' Payment method & TID ')]"
    receive_history_dateTime_header_text="//th[contains(text(),' Date & time ')]"
    receive_history_amount_header_text="//th[contains(text(),' Amount ')]"
    receive_history_entryBy_header_text="//th[contains(text(),' Entry by ')]"
    receive_history_actions_header_text="//th[contains(text(),' Actions ')]"
    
    filter_receivd_history_heading_text=""